# Generated by Django 5.2.7 on 2025-10-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productvariant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'sku')},
        ),
    ]
