# Generated by Django 5.2.7 on 2025-11-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_productvariant_rpd'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='applies_to_type',
            field=models.CharField(choices=[('all_products', 'All Products'), ('specific_products', 'Specific Products')], default='all_products', max_length=32),
        ),
        migrations.AddField(
            model_name='discount',
            name='applies_to_products',
            field=models.ManyToManyField(blank=True, related_name='discounts_applied', to='api.product'),
        ),
    ]
