# Generated by Django 5.2.7 on 2025-11-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_discount_applies_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='device_type',
            field=models.CharField(choices=[('All', 'All'), ('Mobile', 'Mobile'), ('Desktop', 'Desktop')], default='All', max_length=10),
        ),
        migrations.AddField(
            model_name='banner',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower = higher priority'),
        ),
        migrations.AddField(
            model_name='banner',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='Optional link for banner click-through', null=True),
        ),
    ]
