# Generated by Django 5.2.7 on 2025-11-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_homecollageitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecollageitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
