# Generated by Django 5.2.7 on 2025-11-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_homecollageitem_id'),
        ('api', '0009_alter_homecollageitem_item_type'),
    ]

    operations = [
    ]
