# Generated by Django 5.2.7 on 2025-11-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20251122_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='limited_deal_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
