# Generated by Django 5.2.7 on 2025-11-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('reset', 'Password Reset'), ('signup_customer', 'Customer Signup')], max_length=32),
        ),
    ]
