# Generated by Django 5.2.7 on 2025-11-24 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20251122_0241'),
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('comment', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='storefront.customeraccount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='api.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='api.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'order', 'product')},
            },
        ),
    ]
